#!/bin/bash
DIVOLTE_DIRNAME=${PARCEL_DIRNAME:-"Divolte-0.2"}

if [ -n "${JAVA_LIBRARY_PATH}" ]; then
  export JAVA_LIBRARY_PATH="${JAVA_LIBRARY_PATH}:$PARCELS_ROOT/$DIVOLTE_DIRNAME/lib/"
else
  export JAVA_LIBRARY_PATH="$PARCELS_ROOT/$DIVOLTE_DIRNAME/lib/"
fi